# Generated by Django 4.0 on 2021-12-10 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filmes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(default=datetime.datetime(2021, 12, 10, 16, 56, 42, 300498), verbose_name='Publicado em')),
            ],
        ),
    ]
