# Generated by Django 4.0 on 2021-12-10 20:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('data', models.DateTimeField(default=datetime.datetime(2021, 12, 10, 17, 5, 41, 674013), verbose_name='Publicado em')),
            ],
        ),
        migrations.DeleteModel(
            name='filmes',
        ),
    ]
